"""Generate docs/data_quality_report.md from what the pipeline actually did.

Nothing here is hardcoded: every figure comes from the QualityLedger or from
recomputing against the built tables.
"""
from __future__ import annotations

import pandas as pd

from src.cleaning.duplicates import ID_COLLISION, SAME_ENTITY_CONFLICTING
from src.config import DOCS_DIR, UNKNOWN_KEY

STAGES = [
    ("2. Duplicate rescue", "Duplicate rescue"),
    ("3. ID normalization", "ID normalization"),
    ("4. Amount cleaning", "Amount cleaning"),
    ("5. Timestamp cleaning", "Timestamp cleaning"),
    ("6. Status normalization", "Status normalization"),
    ("7. KYC repair", "KYC repair"),
    ("8. Merchant normalization", "Merchant normalization"),
    ("9. Chargeback cleaning", "Chargeback cleaning"),
    ("10. Identity collision analysis", "Identity collision"),
]


def md_table(df: pd.DataFrame) -> str:
    """Render a DataFrame as a GitHub markdown table.

    Hand-rolled so the pipeline carries no `tabulate` dependency — one less
    thing to go wrong on a fresh Streamlit Cloud install.
    """
    cols = [str(c) for c in df.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    for _, row in df.iterrows():
        cells = []
        for v in row:
            if isinstance(v, bool):
                cells.append(str(v))
            elif isinstance(v, float):
                cells.append(f"{v:,.2f}")
            elif isinstance(v, int):
                cells.append(f"{v:,}")
            else:
                cells.append(str(v).replace("|", r"\|"))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _fmt(v) -> str:
    if isinstance(v, bool):
        return str(v)
    if isinstance(v, float):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def _ledger_table(entries: list[dict]) -> str:
    if not entries:
        return "_No transformations recorded for this stage._\n"
    lines: list[str] = []
    for e in entries:
        lines.append(f"#### {e['transformation']}\n")
        lines.append("| Field | Value |")
        lines.append("|---|---|")
        lines.append(f"| BEFORE | {_fmt(e['before'])} |")
        lines.append(f"| AFTER | {_fmt(e['after'])} |")
        lines.append(f"| ROWS AFFECTED | {_fmt(e['rows_affected'])} |")
        lines.append(f"| METHOD | {e['method']} |")
        lines.append(f"| VALIDATION | {e['validation']} |")
        if e.get("reason"):
            lines.append(f"| REASON | {e['reason']} |")
        lines.append("")
    return "\n".join(lines)


def write_report(raw, profile, tables, ledger, fk_checks, independence) -> str:
    fact_tx = tables["fact_transactions"]
    fact_cb = tables["fact_chargebacks"]
    dim_users = tables["dim_users"]
    dim_merchants = tables["dim_merchants"]
    bridge = tables["bridge_identity_collision"]

    out: list[str] = []
    w = out.append

    w("# DataVortex — Data Quality Report")
    w("**Stage 2 · Data Rescue.** _Turning UPI Data Chaos into Fraud Intelligence._\n")
    w("Generated by `scripts/run_pipeline.py`. Every figure below is computed at run time — "
      "nothing in this document is hardcoded.\n")
    w("```")
    w("RAW -> duplicate rescue -> ID normalization -> amount normalization")
    w("    -> timestamp normalization -> status normalization -> MCC normalization")
    w("    -> KYC repair -> chargeback normalization -> identity resolution")
    w("    -> relationship validation -> CLEAN")
    w("```\n")
    w("**Governing principle: no row is ever silently deleted.** Records that cannot be repaired "
      "are retained with a quality flag and a written reason. The only rows removed anywhere in "
      "this pipeline are byte-identical duplicates, and only after proving they are identical on "
      "every column.\n")
    w("---\n")

    w("## 1. Raw dataset overview\n")
    w(md_table(profile))
    w("")
    w("`data/raw/` is immutable — no pipeline step writes to it.\n")

    for title, stage in STAGES:
        w(f"## {title}\n")
        w(_ledger_table(ledger.for_stage(stage)))

        if stage == "Identity collision":
            w("### Why repeated IDs are not duplicates\n")
            for label, dim, key in [
                ("Users", dim_users, "user_key"),
                ("Merchants", dim_merchants, "merchant_key"),
            ]:
                real = dim[dim[key] != UNKNOWN_KEY]
                coll = int((real["identity_class"] == ID_COLLISION).sum())
                same = int((real["identity_class"] == SAME_ENTITY_CONFLICTING).sum())
                uniq = int(len(real) - coll - same)
                w(f"**{label}** — {len(real):,} resolved entities\n")
                w("| Class | Count | Meaning |")
                w("|---|---|---|")
                w(f"| UNIQUE | {uniq:,} | one source row, nothing to reconcile |")
                w(f"| SAME_ENTITY_CONFLICTING | {same:,} | one entity described by several "
                  "conflicting rows — most complete won |")
                w(f"| **ID_COLLISION** | **{coll:,}** | **different entities sharing an ID — "
                  "flagged, never merged** |")
                w("")
            w(f"`BRIDGE_IDENTITY_COLLISION` preserves all {len(bridge):,} candidate rows behind "
              "every repeated ID, so a reviewer can inspect exactly what was set aside.\n")
            conf = dim_users[dim_users["user_key"] != UNKNOWN_KEY]["resolution_confidence"].value_counts()
            w("Resolution confidence on DIM_USERS: "
              + ", ".join(f"`{k}` {v:,}" for k, v in conf.items()) + "\n")

    w("## 11. Foreign-key validation\n")
    w(md_table(fk_checks[[
        "relationship", "left_rows", "raw_match", "raw_match_pct",
        "normalized_match", "normalized_match_pct", "gain_rows", "gain_pp",
        "unmatched_rows", "unmatched_pct",
    ]]))
    w("")
    w("### Is the residual mismatch a cleaning failure?\n")
    w("Tested against the null hypothesis of independent random draws over the observed ID space:\n")
    w(md_table(independence[[
        "pair", "id_space", "left_distinct", "right_distinct",
        "expected_overlap", "observed_overlap", "sd", "z_score", "verdict",
    ]]))
    w("")
    w("A z-score near zero means the overlap is exactly what chance would produce, so **no amount "
      "of normalization can raise it** — the source files drew their user and merchant IDs "
      "independently. The chargeback-to-transaction link, by contrast, is overwhelming, which is "
      "why it is the only relationship used for attribution.\n")
    w("**Unmatched rows are retained, not dropped.** They point at each dimension's `UNKNOWN` "
      "member so that every metric still reconciles to the full transaction count:\n")
    w(f"- transactions with an unresolved user: **{int(fact_tx['user_unresolved'].sum()):,}** "
      f"({100 * fact_tx['user_unresolved'].mean():.2f}%)")
    w(f"- transactions with an unresolved merchant: **{int(fact_tx['merchant_unresolved'].sum()):,}** "
      f"({100 * fact_tx['merchant_unresolved'].mean():.2f}%)")
    w(f"- chargebacks not linked to any transaction: **{int(fact_cb['txn_unlinked'].sum()):,}** "
      f"({100 * fact_cb['txn_unlinked'].mean():.2f}%)\n")

    w("### Analytical coverage (the binding constraint on segmented KPIs)\n")
    linked = fact_cb[~fact_cb["txn_unlinked"]]
    mer_keys = set(dim_merchants.loc[dim_merchants["merchant_key"] != UNKNOWN_KEY, "merchant_key"])
    usr_keys = set(dim_users.loc[dim_users["user_key"] != UNKNOWN_KEY, "user_key"])
    covered_value = fact_tx.loc[~fact_tx["merchant_unresolved"], "amount_inr"].sum()
    coverage = pd.DataFrame([
        ("Transactions resolvable to a KYC record",
         f"{int((~fact_tx['user_unresolved']).sum()):,} ({100 * (~fact_tx['user_unresolved']).mean():.2f}%)"),
        ("Transactions resolvable to a merchant record",
         f"{int((~fact_tx['merchant_unresolved']).sum()):,} ({100 * (~fact_tx['merchant_unresolved']).mean():.2f}%)"),
        ("Transaction value covered by merchant master",
         f"Rs {covered_value:,.0f} ({100 * covered_value / fact_tx['amount_inr'].sum():.2f}%)"),
        ("Chargebacks resolvable to a merchant category",
         f"{int(linked['attributed_merchant_key'].isin(mer_keys).sum()):,} "
         f"({100 * linked['attributed_merchant_key'].isin(mer_keys).mean():.2f}% of linked)"),
        ("Chargebacks resolvable to a KYC record",
         f"{int(linked['attributed_user_key'].isin(usr_keys).sum()):,} "
         f"({100 * linked['attributed_user_key'].isin(usr_keys).mean():.2f}% of linked)"),
    ], columns=["Analysis", "Coverage"])
    w(md_table(coverage))
    w("")
    w("Any 'by merchant category' or 'by KYC status' metric is therefore computed on roughly a "
      "third to a half of the data. The dashboard must display coverage beside every such number.\n")

    w("## 12. Final reconciliation\n")
    w(md_table(_reconciliation(raw, tables)))
    w("")
    w("### Where the KYC and merchant rows went\n")
    w("The negative differences above are **resolution, not deletion**. Every source row is "
      "still accounted for:\n")
    w(md_table(_row_accounting(raw, tables)))
    w("")
    w("A dimension holds one row per entity so that joins cannot fan out. The rows it does not "
      "carry are the non-survivor candidates, and all of them live in "
      "`BRIDGE_IDENTITY_COLLISION` — nothing is discarded, and every set-aside record is "
      "inspectable.\n")
    w("### Transaction value reconciliation\n")
    w(_value_reconciliation(raw["transactions"], fact_tx))
    w("")

    w("## Data quality flag summary\n")
    w(md_table(_flag_summary(fact_tx, fact_cb, dim_users, dim_merchants)))
    w("")

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    path = DOCS_DIR / "data_quality_report.md"
    path.write_text("\n".join(out), encoding="utf-8")
    return str(path)


def _reconciliation(raw, tables) -> pd.DataFrame:
    fact_tx = tables["fact_transactions"]
    fact_cb = tables["fact_chargebacks"]
    dim_users = tables["dim_users"]
    dim_merchants = tables["dim_merchants"]
    rows = [
        ("Transaction rows", len(raw["transactions"]), len(fact_tx),
         "byte-identical duplicate rows collapsed"),
        ("Unique transaction IDs", raw["transactions"]["txn_id"].nunique(), fact_tx["txn_key"].nunique(),
         "unchanged — duplicates shared an ID, they did not add one"),
        ("Chargeback rows", len(raw["chargebacks"]), len(fact_cb),
         "byte-identical duplicate rows collapsed"),
        ("Unique complaint IDs", raw["chargebacks"]["complaint_id"].nunique(), fact_cb["complaint_key"].nunique(),
         "unchanged"),
        ("KYC records", len(raw["kyc"]), len(dim_users) - 1,
         "exact duplicates collapsed, then resolved to one row per user_key; "
         "every candidate preserved in BRIDGE_IDENTITY_COLLISION"),
        ("Merchant records", len(raw["merchants"]), len(dim_merchants) - 1,
         "exact duplicates collapsed, then resolved to one row per merchant_key; "
         "every candidate preserved in BRIDGE_IDENTITY_COLLISION"),
    ]
    df = pd.DataFrame(rows, columns=["Metric", "Raw", "Clean", "Explanation"])
    df.insert(3, "Difference", df["Clean"] - df["Raw"])
    return df[["Metric", "Raw", "Clean", "Difference", "Explanation"]]


def _row_accounting(raw, tables) -> pd.DataFrame:
    """Prove that every source row is either a dimension survivor or in the bridge."""
    bridge = tables["bridge_identity_collision"]
    rows = []
    for label, src, dim, key, etype in [
        ("KYC", raw["kyc"], tables["dim_users"], "user_key", "USER"),
        ("Merchants", raw["merchants"], tables["dim_merchants"], "merchant_key", "MERCHANT"),
    ]:
        exact_dupes = int(src.duplicated().sum())
        after_dedup = len(src) - exact_dupes
        survivors = len(dim) - 1  # exclude the UNKNOWN member
        b = bridge[bridge["entity_type"] == etype]
        non_survivors = int((~b["is_survivor"].astype(bool)).sum())
        rows.append({
            "Source": label,
            "Raw rows": len(src),
            "Exact duplicates collapsed": exact_dupes,
            "Rows after dedup": after_dedup,
            "Dimension survivors": survivors,
            "Non-survivors kept in bridge": non_survivors,
            "Accounted for": survivors + non_survivors,
            "Unaccounted": after_dedup - (survivors + non_survivors),
        })
    return pd.DataFrame(rows)


def _value_frame(tx_raw: pd.DataFrame, fact_tx: pd.DataFrame) -> pd.DataFrame:
    """Value reconciliation as data, so the dashboard need not restate it."""
    from src.cleaning.amounts import parse_amount_series

    raw_vals = parse_amount_series(tx_raw["amount"])["value"]
    dup_rows = tx_raw.duplicated(keep="first")
    steps = [
        ("Raw, signed", float(raw_vals.sum()), "as parsed from source"),
        ("Raw, sign repaired", float(raw_vals.abs().sum()),
         f"abs() applied to {int((raw_vals < 0).sum()):,} sign-corrupted amounts"),
        ("After duplicate removal", float(raw_vals[~dup_rows.values].abs().sum()),
         f"{int(dup_rows.sum()):,} byte-identical rows collapsed"),
        ("FACT_TRANSACTIONS", float(fact_tx["amount_inr"].sum()), "no further change"),
    ]
    out = pd.DataFrame(steps, columns=["step", "total_inr", "cause"])
    out["delta"] = out["total_inr"].diff().fillna(0.0)
    return out


def _value_reconciliation(tx_raw: pd.DataFrame, fact_tx: pd.DataFrame) -> str:
    from src.cleaning.amounts import parse_amount_series

    raw_vals = parse_amount_series(tx_raw["amount"])["value"]
    raw_sum = raw_vals.sum()
    raw_abs_sum = raw_vals.abs().sum()
    dup_rows = tx_raw.duplicated(keep="first")
    dedup_abs_sum = raw_vals[~dup_rows.values].abs().sum()
    clean_sum = fact_tx["amount_inr"].sum()
    residual = clean_sum - dedup_abs_sum
    lines = [
        "| Step | Total (Rs) | Delta vs previous | Cause |",
        "|---|---|---|---|",
        f"| Raw, signed | {raw_sum:,.2f} | — | as parsed from source |",
        f"| Raw, sign repaired | {raw_abs_sum:,.2f} | {raw_abs_sum - raw_sum:+,.2f} | "
        f"abs() applied to {int((raw_vals < 0).sum()):,} sign-corrupted amounts |",
        f"| After duplicate removal | {dedup_abs_sum:,.2f} | {dedup_abs_sum - raw_abs_sum:+,.2f} | "
        f"{int(dup_rows.sum()):,} byte-identical rows collapsed |",
        f"| **FACT_TRANSACTIONS** | **{clean_sum:,.2f}** | {residual:+,.2f} | "
        "no further change — this must be zero |",
        "",
        f"Total transaction value changes **only** for the two documented transformations. "
        f"Residual after both: `{residual:+,.4f}` — "
        f"**{'PASS' if abs(residual) < 0.01 else 'FAIL'}**.",
    ]
    return "\n".join(lines)


def _flag_summary(fact_tx, fact_cb, dim_users, dim_merchants) -> pd.DataFrame:
    real_users = dim_users[dim_users["user_key"] != UNKNOWN_KEY]
    real_mer = dim_merchants[dim_merchants["merchant_key"] != UNKNOWN_KEY]

    def flag(df, col):
        return int(df[col].fillna(False).astype(bool).sum())

    rows = [
        ("FACT_TRANSACTIONS rows", len(fact_tx)),
        ("amount sign-corrupted (repaired + flagged)", flag(fact_tx, "amount_sign_invalid")),
        ("amount unparseable", flag(fact_tx, "amount_missing")),
        ("timestamp unparseable", flag(fact_tx, "timestamp_invalid")),
        ("UTR missing", flag(fact_tx, "utr_missing")),
        ("UTR invalid format among non-blank",
         int((~fact_tx["utr_valid"].fillna(False).astype(bool)
              & ~fact_tx["utr_missing"].fillna(False).astype(bool)).sum())),
        ("transaction MCC unusable", int(fact_tx["mcc_txn_clean"].isna().sum())),
        ("user unresolved -> UNKNOWN", flag(fact_tx, "user_unresolved")),
        ("merchant unresolved -> UNKNOWN", flag(fact_tx, "merchant_unresolved")),
        ("FACT_CHARGEBACKS rows", len(fact_cb)),
        ("chargeback unlinked to transaction", flag(fact_cb, "txn_unlinked")),
        ("chargeback txn_id malformed (wrong width)", flag(fact_cb, "txn_id_malformed")),
        ("cb.user_id conflicts with linked transaction", flag(fact_cb, "cb_userid_conflicts_txn")),
        ("cb.merchant_id conflicts with linked transaction", flag(fact_cb, "cb_merchantid_conflicts_txn")),
        ("disputed_amount missing", flag(fact_cb, "disputed_amount_missing")),
        ("reporting delay negative", flag(fact_cb, "delay_negative")),
        ("reporting delay missing", flag(fact_cb, "delay_missing")),
        ("DIM_USERS entities", len(real_users)),
        ("users flagged identity_ambiguous", flag(real_users, "identity_ambiguous")),
        ("PAN repaired by homoglyph substitution", int((real_users["pan_status"] == "REPAIRED").sum())),
        ("PAN unrepairable (truncated)", int((real_users["pan_status"] == "TRUNCATED").sum())),
        ("income invalid (negative / not available)", flag(real_users, "income_invalid")),
        ("age implausible", flag(real_users, "age_implausible")),
        ("DIM_MERCHANTS entities", len(real_mer)),
        ("merchants flagged identity_ambiguous", flag(real_mer, "identity_ambiguous")),
        ("merchant MCC vs category conflict", flag(real_mer, "category_conflict")),
        ("merchant declared ticket size invalid", flag(real_mer, "ticket_invalid")),
    ]
    return pd.DataFrame(rows, columns=["Metric", "Value"])
