"""Page 4 — Data Quality & Hypothesis Register.

The differentiating page. It shows what the rescue recovered, and then shows
every fraud hypothesis the brief proposed tested against the data — including
the six that do not survive and the one that runs backwards.
"""
from __future__ import annotations

import pandas as pd
import streamlit as st

from app.components import charts
from app.components.theme import SERIES, STATUS, VERDICT_STYLE
from app.components.ui import (
    callout, fmt_inr, fmt_int, fmt_pct, kpi_card, section, verdict_chip,
)


def render(ctx) -> None:
    agg, star = ctx["agg"], ctx["star"]
    st.markdown("# Data Quality & Hypothesis Register")
    st.markdown(
        '<div class="dv-sec-note" style="max-width:58rem">'
        "Two questions a reviewer should be able to answer from this page: what did the "
        "cleaning actually do, and does the system distinguish a real signal from noise. "
        "Every number is read from the generated analytics build."
        "</div>", unsafe_allow_html=True)

    tabs = st.tabs(["Quality scorecard", "Before vs after", "Hypothesis register"])
    with tabs[0]:
        _scorecard(ctx)
    with tabs[1]:
        _before_after(ctx)
    with tabs[2]:
        _register(ctx)


# --------------------------------------------------------------------------
def _scorecard(ctx) -> None:
    agg, star = ctx["agg"], ctx["star"]
    dq = agg["agg_data_quality"]
    tx_all = star["fact_transactions"]
    cb_all = star["fact_chargebacks"]
    users, merchants = star["dim_users"], star["dim_merchants"]

    section("Data quality scorecard",
            "Counts are generated by the pipeline, never hardcoded. Nothing in this table "
            "was deleted — every defect is repaired and flagged, or retained and flagged.")

    rows = [
        ("Duplicate transaction rows collapsed",
         int(-star["recon_rows"].set_index("Metric").loc["Transaction rows", "Difference"]),
         "byte-identical on all 8 columns, verified before collapsing"),
        ("Duplicate complaint rows collapsed",
         int(-star["recon_rows"].set_index("Metric").loc["Chargeback rows", "Difference"]),
         "byte-identical on all 13 fields"),
        ("Amount sign corruption", int(tx_all["amount_sign_invalid"].sum()),
         "repaired to magnitude, flagged; not refunds — no positive twin exists"),
        ("Missing UTR", int(tx_all["utr_missing"].sum()),
         "never fabricated; no UTR collision signal exists once duplicates are removed"),
        ("Malformed chargeback txn_id", int(cb_all["txn_id_malformed"].sum()),
         "5-digit against the 8-digit standard; unrecoverable, retained and flagged"),
        ("Complaints unlinked to a transaction", int(cb_all["txn_unlinked"].sum()),
         "no attributable transaction; excluded from entity metrics, kept in totals"),
        ("Transactions with unresolved merchant", int(tx_all["merchant_unresolved"].sum()),
         "routed to the UNKNOWN dimension member, retained in every total"),
        ("Transactions with unresolved customer", int(tx_all["user_unresolved"].sum()),
         "routed to the UNKNOWN dimension member, retained in every total"),
        ("Customer ID collisions", int(users["identity_ambiguous"].sum()),
         "different people share one ID; all candidates preserved in the bridge table"),
        ("Merchant ID collisions", int(merchants["identity_ambiguous"].sum()),
         "different businesses share one ID; all candidates preserved"),
        ("PAN repaired by homoglyph substitution",
         int((users["pan_status"] == "REPAIRED").sum()),
         "0↔O, 1↔I, 2↔Z, 5↔S, 8↔B applied positionally, kept only when the result is a valid PAN"),
        ("PAN unrepairable (truncated)", int((users["pan_status"] == "TRUNCATED").sum()),
         "9 characters, missing the check letter; fabricating it would invent an identity"),
        ("Reporting delay negative", int(cb_all["delay_negative"].sum()),
         "dispute predates its own transaction timestamp; flagged, not clipped"),
        ("Reporting delay unknown", int(cb_all["delay_missing"].sum()),
         "a timestamp was unparseable; excluded from the delay metric only"),
    ]
    frame = pd.DataFrame(rows, columns=["Defect", "Records", "Treatment"])
    st.dataframe(frame, hide_index=True, width="stretch", height=530,
                 column_config={"Records": st.column_config.NumberColumn(format="localized")})

    section("Attribution coverage", "How much of the book each analysis can actually reach.")
    c = st.columns(4, gap="small")
    cov = [
        ("Chargeback → transaction", 100 * int((~cb_all["txn_unlinked"]).sum()) / len(cb_all),
         "via txn_id, the only trustworthy foreign key"),
        ("Transaction → merchant", 100 * int((~tx_all["merchant_unresolved"]).sum()) / len(tx_all),
         "merchant master coverage"),
        ("Transaction → KYC", 100 * int((~tx_all["user_unresolved"]).sum()) / len(tx_all),
         "KYC record coverage"),
        ("Timestamp with clock time", 100 * int(tx_all["timestamp_time_known"].sum()) / len(tx_all),
         "the rest are date-only and excluded from hourly analysis"),
    ]
    for col, (label, pct, basis) in zip(c, cov):
        with col:
            kpi_card(label, fmt_pct(pct), "", pct, basis)


# --------------------------------------------------------------------------
def _before_after(ctx) -> None:
    star = ctx["star"]
    tx = star["fact_transactions"]

    section("Before versus after cleaning",
            "Row counts reconcile exactly. The only rows removed anywhere in the pipeline are "
            "byte-identical duplicates, and only after proving they are identical on every "
            "column. Every figure here is read from the reconciliation tables the pipeline "
            "writes — none is typed into this page.")

    recon = star["recon_rows"].rename(columns={
        "Metric": "Metric", "Raw": "Raw", "Clean": "Clean",
        "Difference": "Difference", "Explanation": "Explanation"})
    st.dataframe(recon, hide_index=True, width="stretch")

    accounting = star["recon_accounting"]
    unaccounted = int(accounting["Unaccounted"].abs().sum())
    bridge_rows = int(accounting["Non-survivors kept in bridge"].sum())
    callout(
        "<strong>The negative differences are resolution, not deletion.</strong> A dimension "
        "holds one row per entity so joins cannot fan out. Every row it does not carry sits "
        f"in <code>BRIDGE_IDENTITY_COLLISION</code>: {fmt_int(len(star['bridge_identity_collision']))} "
        f"candidate rows, of which {fmt_int(bridge_rows)} are non-survivors — with "
        f"<strong>{unaccounted} rows unaccounted for</strong> on either source.",
        kind="good" if unaccounted == 0 else "crit")

    section("Row accounting", "Survivors plus bridged non-survivors must equal the deduped source.")
    st.dataframe(accounting, hide_index=True, width="stretch")

    section("Transaction value reconciliation",
            "Total value may change only for the two documented transformations.")
    value = star["recon_value"]
    st.dataframe(
        value.rename(columns={"step": "Step", "total_inr": "Total ₹",
                              "delta": "Delta vs previous", "cause": "Cause"}),
        hide_index=True, width="stretch",
        column_config={
            "Total ₹": st.column_config.NumberColumn(format="%.2f"),
            "Delta vs previous": st.column_config.NumberColumn(format="%+.2f"),
        })

    residual = float(value["delta"].iloc[-1])
    callout(
        f"Residual after both documented transformations: <strong>{residual:+,.4f}</strong> — "
        f"<strong>{'PASS' if abs(residual) < 0.01 else 'FAIL'}</strong>. "
        "Nothing else moved the total.",
        kind="good" if abs(residual) < 0.01 else "crit")

    section("Timestamp parsing", "Five formats, dispatched on separator with zero "
                                 "counterexamples across all seven date fields in the bundle.")
    methods = tx["timestamp_parse_method"].value_counts()
    st.plotly_chart(
        charts.hbar(methods.index.tolist(), methods.tolist(),
                    title="Transactions by timestamp parse method",
                    text=[fmt_int(v) for v in methods], xtitle="transactions"),
        width="stretch", config={"displayModeBar": False})
    callout(
        "Slash dates are <code>DD/MM/YYYY</code> and hyphen dates are <code>MM-DD-YYYY</code>. "
        "The rule was established by counting, across all seven date fields, how many rows "
        "prove each position exceeds 12 — thousands support each convention and "
        "<strong>none contradicts either</strong>. Applying one convention to both would "
        "silently mis-date roughly a third of the book.")


# --------------------------------------------------------------------------
def _register(ctx) -> None:
    reg = ctx["agg"]["agg_hypothesis_register"]

    counts = reg["verdict"].value_counts()
    section(
        "Hypothesis register",
        "The dataset notes ship a list of insights students may discover. Each is a plausible "
        "claim and each is testable. Asserting them because they sound like fraud analytics "
        "is the easiest way to publish something false, so every one is tested and reported "
        "whichever way it falls.")

    cols = st.columns(len(counts), gap="small")
    for col, (verdict, n) in zip(cols, counts.items()):
        colour, icon = VERDICT_STYLE.get(verdict, ("#888", "—"))
        with col:
            st.markdown(
                f'<div class="dv-kpi" style="border-left:3px solid {colour}">'
                f'<div class="dv-kpi-label">{icon} {verdict}</div>'
                f'<div class="dv-kpi-value">{n}</div></div>', unsafe_allow_html=True)

    contradicted = reg[reg["verdict"] == "CONTRADICTED"]
    if len(contradicted):
        row = contradicted.iloc[0]
        st.markdown("")
        st.markdown(
            f'<div class="dv-call dv-call-crit" style="border-left-width:5px;padding:1rem 1.1rem">'
            f'<div style="font-size:0.72rem;font-weight:700;letter-spacing:0.06em;'
            f'color:{STATUS["critical"]};margin-bottom:0.35rem">'
            f'✕ CONTRADICTED — THE DATA SHOWS THE OPPOSITE</div>'
            f'<div style="font-size:0.95rem;font-weight:620;color:#0b0b0b;margin-bottom:0.4rem">'
            f'{row["hypothesis"]}</div>'
            f'<div style="font-size:0.83rem;line-height:1.6">{row["reading"]}</div>'
            f'<div style="font-size:0.75rem;color:#898781;margin-top:0.5rem">'
            f'{row["test"]} · {row["statistic"]} · p = {row["p_value"]}</div>'
            f'</div>', unsafe_allow_html=True)

    section("All tested hypotheses")
    order = {"CONTRADICTED": 0, "BORDERLINE": 1, "SUPPORTED": 2,
             "QUANTIFIED": 3, "NOT SUPPORTED": 4, "UNTESTABLE": 5}
    ordered = reg.assign(_o=reg["verdict"].map(order).fillna(9)).sort_values("_o")

    for _, row in ordered.iterrows():
        with st.container(border=True):
            head, chip = st.columns([5, 1])
            with head:
                st.markdown(
                    f'<div style="font-size:0.92rem;font-weight:620;color:#0b0b0b">'
                    f'{row["hypothesis"]}</div>'
                    f'<div style="font-size:0.72rem;color:#898781;margin-top:2px">'
                    f'source: {row["source"]}</div>', unsafe_allow_html=True)
            with chip:
                st.markdown(
                    f'<div style="text-align:right">{verdict_chip(row["verdict"])}</div>',
                    unsafe_allow_html=True)
            st.markdown(
                f'<div style="font-size:0.82rem;color:#52514e;line-height:1.6;'
                f'margin-top:0.4rem">{row["reading"]}</div>', unsafe_allow_html=True)
            st.markdown(
                f'<div style="font-size:0.73rem;color:#898781;margin-top:0.5rem;'
                f'font-family:ui-monospace,SFMono-Regular,Menlo,monospace">'
                f'{row["test"]} · {row["statistic"]}'
                f'{" · p = " + str(row["p_value"]) if pd.notna(row["p_value"]) else ""}</div>',
                unsafe_allow_html=True)

    section("Why this matters")
    notes_rows = reg[reg["source"] == "track1_dataset_notes.txt"]
    rejected = int(notes_rows["verdict"].isin(["NOT SUPPORTED", "CONTRADICTED"]).sum())
    backwards = int((reg["verdict"] == "CONTRADICTED").sum())
    callout(
        "A system that labels everything suspicious is worthless — it generates work "
        f"without information. {rejected} of the {len(notes_rows)} insights suggested by "
        "the dataset notes do not survive testing on this data"
        + (f", and {backwards} runs in the opposite direction to its claim" if backwards else "")
        + ". Reporting that is more useful to a payments risk team than a confident "
        "dashboard built on noise, because it tells them which controls <em>not</em> to build.")
